---
driver_plugin: vagrant

provisioner:
  require_chef_omnibus: true

platforms:
  - name: centos-7.2
  - name: ubuntu-14.04

verifier:
  name: inspec

suites:
  - name: default
    run_list:
      - recipe[nginx-sample::default]
    attributes:
