name 'nginx-sample'
maintainer 'Ed Bartholomew'
maintainer_email ''
license 'all_rights'
description 'Installs/Configures nginx-sample'
long_description 'Installs/Configures nginx-sample'
version '0.1.0'
